# Those hparams which are in a list 
# apply differently to each ntwrk
# Should match with NUM_AGENTS_PER_TYPE

"LR": [0.001]  # HP (v2_Exec_FixedQuantsComplex_Ablations) shows 0.001 better than 0.0005 and 0.0015 (But only marginally) 
"NUM_ENVS": 4096 #2048 #2048 #128
"NUM_STEPS": 126
"NUM_STEPS_EVAL" : 63
"GRU_HIDDEN_DIM": 128
"FC_DIM_SIZE": 128
"TOTAL_TIMESTEPS": 2e7
"UPDATE_EPOCHS": 8
"NUM_MINIBATCHES": 8
"GAMMA": [0.99] # HP (v2_Exec_FixedQuantsComplex_Ablations) shows 0.99 better than 0.999
"GAE_LAMBDA": [0.9999]
"CLIP_EPS": 0.2
"SCALE_CLIP_EPS": [False]
"ENT_COEF": [0.001]
"VF_COEF": [5e-5]
"MAX_GRAD_NORM": [0.5]
"ACTIVATION": ["relu"]
"ENV_NAME": "JAXMARL-SingleExec-v0"
"NUM_AGENTS_PER_TYPE": [1]
"SEED": 2
"N_DEVICES": 1
"ENV_CONFIG": "config/env_configs/exec_debug_fixed_quants_complex.json"
"ANNEAL_LR": [False]

# WandB Params
"ENTITY": "oxford-lob"
"PROJECT": "v4_Exec_FixedQuantsComplex_Ablations" #"v4_2Player_reference_price_ablation" #"DEBUG"
"WANDB_MODE" : "online"

SWEEP_PARAMETERS:
        LR:
          values: [[0.001],[0.0001]]
        # NUM_STEPS:
        #   values: [32,config["NUM_STEPS"], 512]
        GAE_LAMBDA:
          values: [ [0.999],[0.9999]] #Should smooth value func
        GAMMA:
          values: [ [0.99],[0.999]] #Discoutn factor
        NUM_MINIBATCHES:
          values: [8,16] # Bigger batches, potentially less noisy updates
        # ENT_COEF:
        #   values: [config["ENT_COEF"], [0.1,0.1], [0.05,0.05]]
        # UPDATE_EPOCHS:
        #   values: [config["UPDATE_EPOCHS"], 8]
        # CLIP_EPS:
        #   values: [config["CLIP_EPS"], 0.3, 0.1]
        # VF_COEF:
        #   values: [config["VF_COEF"], [1e-6,1e-7], [1e-9,1e-8]]
        # FC_DIM_SIZE:
        #   values: [config["FC_DIM_SIZE"], 256]
        # NUM_AGENTS_PER_TYPE:
        #   values: [config["NUM_AGENTS_PER_TYPE"], [2,2], [10,10]]
        SEED:
          values: [42,37]
        # NUM_ENVS:
        #   values: [config["NUM_ENVS"]]
        # NUM_STEPS:
        #   values: [config["NUM_STEPS"], 128, 32, 8]
        AGENT_CONFIGS:
          parameters:
            # MarketMaking:
            #   parameters:
            #     inv_penalty:
            #       values: ['none']  # "none" "linear "quadratic"
            #     skew_multiplier:
            #       values: [10]
            #     action_space:
            #       values: ["fixed_quants"]  #"spread_skew",,"fixed_quants"simple
            #     reward_space:
            #       values: ["spooner","buy_sell_pnl"]  # "spooner"buy_sell_pnl
            #     reference_price_portfolio_value:
            #       values: ["best_bid_ask"]  #best_bid_ask "mid"
            Execution:
              parameters:
                reward_lambda:
                  values: [0.0,0.3] #,0.2,0.8,1.0]
                doom_price_penalty:
                  values: [5,10]
                # fixed_quant_value:
                #   values: [10]
                # n_actions:
                #   values: [2,4,3]  #fixed_quants,fixed_quants_complex
                # reward_scaling_quo:
                #   values: [100.0]




# High-Level Params
"CALC_EVAL" : True
"TimePeriod" : "2024"
"EvalTimePeriod" : "2024_Dec"
"Calculate Baseline" : False
"Timing" : False



