# Those hparams which are in a list 
# apply differently to each ntwrk
# Should match with NUM_AGENTS_PER_TYPE

"LR": [0.0004, 0.0004]
"NUM_ENVS": 512
"NUM_STEPS": 256
"GRU_HIDDEN_DIM": 128
"FC_DIM_SIZE": 128
"TOTAL_TIMESTEPS": 5e7
"UPDATE_EPOCHS": 4
"NUM_MINIBATCHES": 16
"GAMMA": [0.999, 0.999]
"GAE_LAMBDA": [0.99, 0.99]
"CLIP_EPS": 0.2
"SCALE_CLIP_EPS": [False]
"ENT_COEF": [0.001, 0.01]
"VF_COEF": [0.000000000000000000000001, 0.00001]
"MAX_GRAD_NORM": [0.5, 0.5]
"ACTIVATION": ["relu", "relu"]
"ENV_NAME": "JAXMARL-Lob-v0"
"NUM_AGENTS_PER_TYPE": [1, 1]
"SEED": 1
"N_DEVICES": 1
"ENV_CONFIG": "config/env_configs/2_player_fq_fqc.json"
"ANNEAL_LR": [True, True]
"NUM_STEPS_EVAL": 256

# WandB Params
"ENTITY": "your-wandb-entity"
"PROJECT": "JAXMARL-LOB_GOOG_2019_two_agents"
"WANDB_MODE" : "disabled"

# High-Level Params
"CALC_EVAL" : False
"TimePeriod" : "2024"
"EvalTimePeriod" : "2024"
"Calculate Baseline" : False
"Timing" : False